version: '2.2'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD=${PG_PASS}
      POSTGRES_DB=${PG_DB}
      POSTGRES_USER=${PB_USER}
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "3000:3000"
    links:
      - postgres
    environment:
      POSTGRES_PASSWORD=${PG_PASS}
      POSTGRES_DB=${PG_DB}
      POSTGRES_USER=${PB_USER}
