package actions

import (
	"boiler/models"
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v5"
	"github.com/gobuffalo/x/responder"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Videocall)
// DB Table: Plural (videocalls)
// Resource: Plural (Videocalls)
// Path: Plural (/videocalls)
// View Template Folder: Plural (/templates/videocalls/)

// VideocallsResource is the resource for the Videocall model
type VideocallsResource struct {
	buffalo.Resource
}

// List gets all Videocalls. This function is mapped to the path
// GET /videocalls
func (v VideocallsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	videocalls := &models.Videocalls{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Videocalls from the DB
	if err := q.All(videocalls); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("videocalls", videocalls)
		return c.Render(http.StatusOK, r.HTML("/videocalls/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(videocalls))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(videocalls))
	}).Respond(c)
}

// Show gets the data for one Videocall. This function is mapped to
// the path GET /videocalls/{videocall_id}
func (v VideocallsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Videocall
	videocall := &models.Videocall{}

	// To find the Videocall the parameter videocall_id is used.
	if err := tx.Find(videocall, c.Param("videocall_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("videocall", videocall)

		return c.Render(http.StatusOK, r.HTML("/videocalls/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(videocall))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(videocall))
	}).Respond(c)
}

// New renders the form for creating a new Videocall.
// This function is mapped to the path GET /videocalls/new
func (v VideocallsResource) New(c buffalo.Context) error {
	c.Set("videocall", &models.Videocall{})

	return c.Render(http.StatusOK, r.HTML("/videocalls/new.plush.html"))
}

// Create adds a Videocall to the DB. This function is mapped to the
// path POST /videocalls
func (v VideocallsResource) Create(c buffalo.Context) error {
	// Allocate an empty Videocall
	videocall := &models.Videocall{}

	// Bind videocall to the html form elements
	if err := c.Bind(videocall); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(videocall)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("videocall", videocall)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/videocalls/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "videocall.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/videocalls/%v", videocall.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(videocall))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(videocall))
	}).Respond(c)
}

// Edit renders a edit form for a Videocall. This function is
// mapped to the path GET /videocalls/{videocall_id}/edit
func (v VideocallsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Videocall
	videocall := &models.Videocall{}

	if err := tx.Find(videocall, c.Param("videocall_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("videocall", videocall)
	return c.Render(http.StatusOK, r.HTML("/videocalls/edit.plush.html"))
}

// Update changes a Videocall in the DB. This function is mapped to
// the path PUT /videocalls/{videocall_id}
func (v VideocallsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Videocall
	videocall := &models.Videocall{}

	if err := tx.Find(videocall, c.Param("videocall_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Videocall to the html form elements
	if err := c.Bind(videocall); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(videocall)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("videocall", videocall)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/videocalls/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "videocall.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/videocalls/%v", videocall.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(videocall))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(videocall))
	}).Respond(c)
}

// Destroy deletes a Videocall from the DB. This function is mapped
// to the path DELETE /videocalls/{videocall_id}
func (v VideocallsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Videocall
	videocall := &models.Videocall{}

	// To find the Videocall the parameter videocall_id is used.
	if err := tx.Find(videocall, c.Param("videocall_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(videocall); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "videocall.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/videocalls")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(videocall))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(videocall))
	}).Respond(c)
}
